---
# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================


logging:
  level:
    ROOT: INFO

spring:
  kafka:
    bootstrap-servers: localhost:9092

    streams:
      bootstrap-servers: localhost:9092
      state-dir: ./state-dir/kafka
server:
  port: 8081