name: Test

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'

      - name: Maven version
        run: mvn --version
      - name: Test with Maven
        run: mvn -B verify
